project:
  type: website
  output-dir: docs

language:
  search-text-placeholder: Szukaj
  
website:
  favicon: images/favicon/favicon.ico
  back-to-top-navigation: true
  search:
    location: sidebar
    type: textbox
  page-footer:
    left:
      - text: "IAD III 2025"
    right:
      - text: "© 2025 Tomasz Golecki | Tomasz Hanusek | Damian Spodar"
    center:
      - text: "Projekt z Zakresu Analizy Danych"
  page-navigation: true
  navbar:
    pinned: true
    left:
      - text: "Strona Główna"
        href: index.qmd
        icon: box-seam
      - text: "Aplikacja"
        href: aplikacja.qmd
        icon: code-slash
      - text: "Sprawozdanie"
        href: sprawozdanie.qmd
        icon: book
      - text: "Dataset"
        href: "https://www.kaggle.com/datasets/noeyislearning/framingham-heart-study"
        icon: database
      - text: "Politechnika Lubelska"
        href: "https://pollub.pl/"
        icon: rocket-takeoff
      - text: "Kontakt"
        href: kontakt.qmd
        icon: people
    right:
      - href: "https://github.com/tgolecki04/Heart-Disease-Prediction"
        icon: github
  sidebar:
    style: "docked"
    logo: "images/article/logo_pollub.jpg"
    contents:
      - text: '<i class="bi bi-dot"></i>Wstęp <i class="bi bi-chat-left-text"></i>'
        href: index.qmd
      - text: '<i class="bi bi-dot"></i>Plan Projektu <i class="bi bi-box-seam"></i>'
        href: plan.qmd
      - text: '<i class="bi bi-dot"></i>Dane & Analiza <i class="bi bi-clipboard-data"></i>'
        href: dane.qmd
      - text: '<i class="bi bi-dot"></i>Modele <i class="bi bi-cpu"></i>'
        href: modele.qmd
      - text: '<i class="bi bi-dot"></i>Wnioski <i class="bi bi-clipboard-check"></i>'
        href: wnioski.qmd
      - text: '<i class="bi bi-dot"></i>Zakończenie <i class="bi bi-book"></i>'
        href: zakonczenie.qmd 
      - text: '<i class="bi bi-dot"></i>Literatura <i class="bi bi-journal-code"></i>'
        href: literatura.qmd 
    

format:
  html:
    theme:
      light: styles/sandstone.scss
      dark: styles/sandstone-custom.scss
    fontsize: 16px
    css: styles/styles.css
    toc: true
    toc-title: "Spis treści"
    number-sections: true
    title-block-banner: "#947E76"
    title-block-banner-color: "#fcfffd"
    code-fold: show
    code-tools: true
    code-summary: "Pokaż/Ukryj Kod"
df-print: kable
